### ISSUE TITLE
Reading existing Private KEY throws DataError

### ISSUE THREAD

**Issue by alfredomova** [GlobalSign/PKI.js#53] opened 2016-03-18 07:11 UTC
Loading an existing private key from a .KEY file throws me this error:

_DataError: Data provided to an operation does not meet requirements_

I'm passing the arraybuffer to the recipientPrivateKey parameter at the moment of opening the envelop,

[http://stackoverflow.com/questions/36075081/read-private-key-in-key-format-with-pki-js-for-cms-envelopeddata](url)

**Comment by YuryStrozhevsky** [comment] 2016-03-18 07:38
There is no such text inside PKIjs. Thus the error came from standard WebCrypto engine. Thus you pass a wrong data to PKIjs.

Please put here BASE64 encoded "recipientPrivateKey". Or send it to my e-mail (in GitHub profile).

**Comment by alfredomova** [comment] 2016-03-18 14:47
the private key, certificate and password are generated, here in México, by the SAT([http://www.sat.gob.mx/](http://www.sat.gob.mx/)), 
I have made a similar example to sign documents, in that example I used [JSRSASIGN](https://github.com/kjur/jsrsasign), and using the same cert+key+pass as with this, I read the local file and pass it as a B64 string and it works, this is the example: [https://github.com/alfredomova/firmaJs-with-jsrsasign-example](https://github.com/alfredomova/firmaJs-with-jsrsasign-example)
with this PKIJS, the only difference is that I can pass the array buffer instead of the b64 string

**Comment by alfredomova** [comment] 2016-03-18 15:15
here is the code:
[https://github.com/alfredomova/CMS-EnvelopedData-Example-with-PKI.js](https://github.com/alfredomova/CMS-EnvelopedData-Example-with-PKI.js)

**Comment by rmhrisk** [comment] 2016-03-18 17:24
@alfredomova, unfortunately, the issue here is that WebCrypto itself is not happy with the format of the base64 blob you are providing. Without looking at that blob we can not help you diagnose what that issue is.

The thing that may not be obvious is that there are many formats a private key can be packaged as, for example, it might be an encrypted PKCS#8, PKCS#5, OpenSSL key blobs, PKCS #12 or one of many other formats.

Things are further complicated since there encoding and encryption options as well. 

Again the issue here is not that PKIjs can not use your key, it is that WebCrypto does not like the format in which it is provided. Once it is understood what input data you are providing we can recommend what transformation you will need to do if you want to import that key into WebCrypto.

I know jsrsasign supports both PKCS #8 and PKCS #5 so it is likely one of these, the question then becomes which one and what options are used in its construction.

**Comment by alfredomova** [comment] 2016-03-18 18:27
sorry I can't share the certificate but it is my personal,

with JSRSASIGN the method used is **getKeyFromEncryptedPKCS8PEM**, in the API ref:

<static> {Object} PKCS5PKEY.getKeyFromEncryptedPKCS8PEM(pkcs8PEM, passcode)
get RSAKey/ECDSA private key object from encrypted PEM PKCS#8 private key
Parameters:
{String} pkcs8PEM
    string of PEM formatted PKCS#8 private key
{String} passcode
    passcode string to decrypt key
Since:
    pkcs5pkey 1.0.5
Returns:
    {Object} RSAKey or KJUR.crypto.ECDSA private key object 

so it is a _PEM formated PKCS8,_
and in the properties that I can read of that object:

_Type: RSA 
is private key?: true_

![2016-03-18 1](https://cloud.githubusercontent.com/assets/2198158/13887988/63d3f964-ed04-11e5-8d7e-f679383c5099.png)

hope this helps :(

**Comment by rmhrisk** [comment] 2016-03-18 20:19
Do you know what algorithm the key is encrypted with? Do you know what algorithm and curve the key is?

**Comment by rmhrisk** [comment] 2016-03-18 20:23
Also please look at this : https://github.com/kjur/jsrsasign/wiki/Tutorial-for-PKCS5-and-PKCS8-PEM-private-key-formats-differences and say what headers you have around your key.

**Comment by rmhrisk** [comment] 2016-03-18 20:27
Also what browser are you using?

**Comment by alfredomova** [comment] 2016-03-18 21:31
the headers that I used are like this:
```
			var pkcs8PEM = "" +
			"-----BEGIN ENCRYPTED PRIVATE KEY-----\r\n" +
			$('#key_b64').val() 
			"-----END ENCRYPTED PRIVATE KEY-----\r\n";
```
the algorithm, I think, it's rsa with sha1,
so far I tried with Firefox 44.0.2 and Chrome 49.0.2623.87 m

**Comment by rmhrisk** [comment] 2016-03-18 21:40
Are those the headers on the private key or the ones you have added?

**Comment by alfredomova** [comment] 2016-03-18 21:45
no, I have to add them manually, and then pass that string plus the password to this method:

`PKCS5PKEY.getKeyFromEncryptedPKCS8PEM(pkcs8PEM, passcode) `

and in that way I'm sure the .KEY is good, or at least with JSRSASIGN is working,

**Comment by rmhrisk** [comment] 2016-03-18 21:47
I am trying to find out what the key actually is without that I can't help. You adding a header doesn't make it a given format. 

Webcrypto is saying it is not good, that is potentially the format type.

What does the source file have as its headers? Absent that how was the key created and with which options?

**Comment by alfredomova** [comment] 2016-03-18 23:49
I'm sorry, I'm not expert in security nor cryptography jeje, 

but taking that b64 with those headers are working for me with _**JSRSASIGN**_,
by itself, in the b64 string I don't know if there are more or less headers b'cos it's just the characters as it is shown in the image i uploaded before,

but with this PKI.JS, I'm not using that string b64, I'm passing the arraybuffer directly in:

   ```
         cms_enveloped_simp.decrypt(0,
                {
                    recipientCertificate: cert_simpl,
                    recipientPrivateKey: privateKeyBuffer   <<<< HERE
```

privateKeyBuffer is the arrayBuffer that reads the HTML5's File API directly,

if you check the example that I uploaded you will see that the headers are not been added to try to open the envelop,  [https://github.com/alfredomova/CMS-EnvelopedData-Example-with-PKI.js](https://github.com/alfredomova/CMS-EnvelopedData-Example-with-PKI.js ), 

even in the documentation example ([https://pkijs.org/examples/CMSEnvelopedExample.html](https://pkijs.org/examples/CMSEnvelopedExample.html)) they add the header to show, but then remove them to use the content and then parse it to an arraybuffer and use it to decript

I don't have any information about the .KEY file, about how it is constructed, as I  said before, here in México, those certificates and private keys are generated by the SAT (Sistema de Administración Tributaria)

I don't know if I'm missing something else :'(

**Comment by rmhrisk** [comment] 2016-03-19 00:02
Base64 is not a "format" it is just a way to encode binary data in ASCII, the fact that the key has been base64 encoded tells me nothing about what that binary data is.

Here is what we know:
- The error you are receiving is coming from WebCrypto, and not PKIjs.
- The point in which PKIjs would be invoking WebCrypto based on your sample code is importing the key.

What we do not know is:
- What format the key is in,
- What options were used in that format to protect it.
- What tool was used to create the key
- What options were used with the tool to create the key

We can not answer these questions withou:
a) having a copy of a key that we can look at,
b) being told 
  - what format the key is in,
  - what options are used to protect the key.

Unfortunately this means there is no way for us to help you. The problem is with the format of the input to WebCrypto and without knowing those details there is zero we can do.

I am closing this bug, if your situation changes I would be happy to help but there is nothing more I can do without more information.

Ryan

**Comment by alfredomova** [comment] 2016-03-19 20:45
I have an expired certificate that I used to use for testing, I can send it to you,
it has the same structure and it works for signing with jsrsasign,
could you tell me your email to send it

**Comment by rmhrisk** [comment] 2016-03-19 21:20
send to rmh@unmitigatedrisk.com

**Comment by rmhrisk** [comment] 2016-03-20 20:34
OK I looked at this key with OpenSSL, the key is encoded as DER so to determine what it is we need to parse the ASN.1:

```
openssl asn1parse -in TOSJ821128SL3.key -inform DER 
```

This tells gives us something like this:
```
    0:d=0  hl=4 l= 710 cons: SEQUENCE          
    4:d=1  hl=2 l=  64 cons: SEQUENCE          
    6:d=2  hl=2 l=   9 prim: OBJECT            :PBES2
   17:d=2  hl=2 l=  51 cons: SEQUENCE          
   19:d=3  hl=2 l=  27 cons: SEQUENCE          
   21:d=4  hl=2 l=   9 prim: OBJECT            :PBKDF2
   32:d=4  hl=2 l=  14 cons: SEQUENCE          
   34:d=5  hl=2 l=   8 prim: OCTET STRING      [HEX DUMP]:BE6C892B16C6CF5D
   44:d=5  hl=2 l=   2 prim: INTEGER           :0800
   48:d=3  hl=2 l=  20 cons: SEQUENCE          
   50:d=4  hl=2 l=   8 prim: OBJECT            :des-ede3-cbc
   ...
   ...
```

This looks like a PKCS5 key blob to me which isn't supported by WebCrypto, though to be honest it's been a while so we should have @YuryStrozhevsky confirm.

Regardless it is encrypted using des-ede3-cbc, this is Tripple DES which has an effective key strength of 112 bits. 112bits is generally speaking considered insufficient these days which is why WebCrypto does not support it.

A good resource for effective key strength guidelines is: https://www.keylength.com/en/8/

We should be able to convert this to a PKCS8 and encrypt it with a modern crypto algorithm using this command:

```
openssl pkcs8 -in TOSJ821128SL3.key -topk8 -inform DER -out TOSJ821128SL3-AES.key -outform PEM -v2 aes-256-cbc
```

But I am getting an ASN1 decoding problem:

```
unable to load key
140735213518928:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1198:
140735213518928:error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error:tasn_dec.c:762:
140735213518928:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:694:Field=version, Type=RSA
140735213518928:error:04093004:rsa routines:OLD_RSA_PRIV_DECODE:RSA lib:rsa_ameth.c:119:
140735213518928:error:0D0680A8:asn1 encoding routines:ASN1_CHECK_TLEN:wrong tag:tasn_dec.c:1198:
140735213518928:error:0D06C03A:asn1 encoding routines:ASN1_D2I_EX_PRIMITIVE:nested asn1 error:tasn_dec.c:762:
140735213518928:error:0D08303A:asn1 encoding routines:ASN1_TEMPLATE_NOEXP_D2I:nested asn1 error:tasn_dec.c:694:Field=version, Type=PKCS8_PRIV_KEY_INFO
```

@YuryStrozhevsky can confirm if the issue is me using the wrong command lines or the ASN1 in question is busted.

**Comment by alfredomova** [comment] 2016-03-23 22:15
is it possible to open the envelop generated by PKI.JS with another tool like Bouncy Castle?

**Comment by rmhrisk** [comment] 2016-03-23 22:17
@YuryStrozhevsky can you look at this ASN.1 and see what I am missing?

**Comment by rmhrisk** [comment] 2016-03-23 22:17
@alfredomova yes, 100% of PKIJS is standards based.

**Comment by alfredomova** [comment] 2016-03-24 14:59
Yes! opening the envelop with the CERT + KEY + PASSWORD works with Bouncy Castle, the only extra library that I had to use was Not-Yet-Common-SSL to read the private key from a file

**Comment by rmhrisk** [comment] 2016-03-24 15:36
Great, can we close this?

**Comment by alfredomova** [comment] 2016-03-25 14:56
I was just trying to validate that the envelop was good, but I still can't open it within PKI.JS

**Comment by rmhrisk** [comment] 2016-03-25 17:48
@alfredomova To be clear it is not PKIjs that can not open this key, it is WebCrypto. The key is encoded in an old format and is encrypted with a weaker algorithm that WebCrypto does not support. PKIjs does not implement crypto, it uses the browser provided crypto library (webcrypto).

@YuryStrozhevsky looked at the file, yes in addition to being encrypted with 3DES it is encoded as a PKCS#5 which is not supported by WebCrypto so to import it into WebCrypto it has to be converted to a PKCS8 and re-encrypted with a supported algorithm.

Neither he or I are clear why OpenSSL pkcs8 tool won't open it. @kjur, Urushima-san, neither @yury or I have much experience with PKCS#5 it seems you implemented it in your library, any idea why my OpenSSL command line here:
```
openssl pkcs8 -in TOSJ821128SL3.key -topk8 -inform DER -out TOSJ821128SL3-AES.key -outform PEM -v2 aes-256-cbc
```

Doesn't convert @alfredomova's key to PKCS8 and encrypt as AES? Can he do that with your library?

**Comment by kjur** [comment] 2016-03-27 05:45
W3C WebCrypto standard and its implementations support very limited modern cryptographic algorithms which may raise interoperability issues. Default PBKDF2 algorithm for PKCS#8 of OpenSSL is pbeWithMD5AndDES-CBC. That means most of PKCS#8 encrypted private key can't be loaded by WebCryto. To avoid such kind of issue, we would be better to use plain private key. Otherwise we should specify strong crypto for PBKDF2 such like AES as Ryan-san says.

**Comment by rmhrisk** [comment] 2016-03-27 05:48
@kjur-san thank you.

@alfredomova I am sorry, I am not sure how to convert your private key to a PKCS#8, for you to use WebCrypto and PKIjs for signing you will need to do that. It is really a OpenSSL question maybe the OpenSSL forums can help you. Good luck.

**Closed by rmhrisk** 2016-03-27 05:48 UTC
